horstoeko\orderx\entities\comfort\ram\ProductCharacteristicType:
    properties:
        typeCode:
            expose: true
            access_type: public_method
            serialized_name: TypeCode
            xml_element:
                cdata: false
                namespace: 'urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128'
            accessor:
                getter: getTypeCode
                setter: setTypeCode
            type: horstoeko\orderx\entities\comfort\udt\CodeType
        description:
            expose: true
            access_type: public_method
            serialized_name: Description
            xml_element:
                cdata: false
                namespace: 'urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128'
            accessor:
                getter: getDescription
                setter: setDescription
            type: string
        value:
            expose: true
            access_type: public_method
            serialized_name: Value
            xml_element:
                cdata: false
                namespace: 'urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:128'
            accessor:
                getter: getValue
                setter: setValue
            type: string
