horstoeko\orderx\entities\comfort\ram\ProductCharacteristicType:
    properties:
        description:
            -
                NotNull:
                    groups:
                        - xsd_rules
        value:
            -
                NotNull:
                    groups:
                        - xsd_rules
