horstoeko\orderx\entities\comfort\ram\ProductClassificationType:
    properties:
        classCode:
            -
                NotNull:
                    groups:
                        - xsd_rules
